// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Migrations.Oracle.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.Property<int>("CodigoEmpresa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODEMPRESA");

                    b.Property<string>("NumeroContrato")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("NUMCONTRDIV");

                    b.Property<string>("Bairro")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DCRBAICLI");

                    b.Property<int>("Cep")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Cidade")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DCRCIDCLI");

                    b.Property<string>("CodigoChaveBanco")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODCHAVEBANCO");

                    b.Property<int>("CodigoEnderecoCobranca")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODENDCOBR");

                    b.Property<string>("Complemento")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DCRCOMPLEMENTO");

                    b.Property<long>("CpfCnpj")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CODCPFCNPJCLI");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATCADENDCLI");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATCANCENDCLI");

                    b.Property<DateTime?>("DataEnderecoConferido")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATCONFENDCLI");

                    b.Property<DateTime?>("DataHoraRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REGTIMESTAMP");

                    b.Property<DateTime>("DataRemessaArquivo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATREMARQ");

                    b.Property<DateTime?>("DataRetorno")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATRETARQ");

                    b.Property<string>("DescricaoReferencia")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DCRREFCLI");

                    b.Property<string>("Logradouro")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("DCRENDCLI");

                    b.Property<int?>("NumeroLogradouro")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMENDCLI");

                    b.Property<string>("Observacao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OBSENDCLI");

                    b.Property<int>("OrigemEndereco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORGENDCLI");

                    b.Property<string>("RegistroTransferido")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REGCKTRANSF");

                    b.Property<string>("SitEnderecoConferido")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SITCONFENDCLI");

                    b.Property<string>("SituacaoBloqCorresp")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SITBLOQCORRESPENDCLI");

                    b.Property<int>("SituacaoEnderecoPrincipal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SITENDPRINC");

                    b.Property<int>("SituacaoPrioridadeEndereco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SITPRIORENDCOBR");

                    b.Property<int>("StatusEndereco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STAENDCLI");

                    b.Property<int>("TipoEndereco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPENDCLI");

                    b.Property<string>("Uf")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODUFCLI");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODUSERALTENDCLI");

                    b.Property<string>("UsuarioCadastro")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODUSERCADCLI");

                    b.Property<string>("UsuarioCancelamento")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODUSERCANCENDCLI");

                    b.HasKey("CodigoEmpresa", "NumeroContrato");

                    b.HasIndex("Logradouro", "Cep");

                    b.ToTable("CO092", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Asset", b =>
                {
                    b.Property<int>("CodigoEmpresa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODEMPRESA");

                    b.Property<string>("NumeroContrato")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("NUMCONTRDIV");

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMANOFABBEM");

                    b.Property<int>("AnoModelo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMANOMODELO");

                    b.Property<string>("Chassi")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NUMCHASSIBEM");

                    b.Property<string>("CodigoCertificado")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODCERTBEM");

                    b.Property<string>("CodigoFipe")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODFIPE");

                    b.Property<string>("CodigoMolicar")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODMOLICARVEIC");

                    b.Property<string>("CodigoSinistro")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODSINISTBEM");

                    b.Property<string>("Cor")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DCRCORBEM");

                    b.Property<DateTime>("DataAtualizacaoRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATATUALREG");

                    b.Property<DateTime?>("DataHoraRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REGTIMESTAMP");

                    b.Property<DateTime>("DataRemessaArquivo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATREMARQ");

                    b.Property<string>("DescricaoBem")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DCRBEM");

                    b.Property<string>("Marca")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DCRMARCABEM");

                    b.Property<string>("Modelo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DCRMODELBEM");

                    b.Property<string>("Placa")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NUMPLACABEM");

                    b.Property<string>("RegistroTransferido")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REGCKTRANSF");

                    b.Property<string>("Renavam")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NUMRENAVAMBEM");

                    b.Property<string>("SituacaoGarantia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SITGARANTBEM");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPBEM");

                    b.Property<int>("TipoCombustivel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPCOMBBEM");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VALORBEM");

                    b.Property<decimal?>("ValorCotacao")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VLRCOTACAO");

                    b.HasKey("CodigoEmpresa", "NumeroContrato");

                    b.ToTable("CO004", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Client", b =>
                {
                    b.Property<int>("CodigoEmpresa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODEMPRESA");

                    b.Property<string>("NumeroContrato")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("NUMCONTRDIV");

                    b.Property<string>("CodigoClienteEmpresa")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODCLIEMP");

                    b.Property<string>("CodigoCorrespondenciaCliente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODCORRESPCLI");

                    b.Property<int?>("CodigoEstadoCivil")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODESTADOCIVIL");

                    b.Property<int?>("CodigoFilial")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODFILIAL");

                    b.Property<long>("CpfCnpj")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CODCPFCNPJCLI");

                    b.Property<DateTime?>("DatNascCliente")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATNASCCLI");

                    b.Property<DateTime>("DataAtualizacaoRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATATUALREG");

                    b.Property<DateTime?>("DataCadastroCliente")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATCADCLI");

                    b.Property<DateTime?>("DataHoraRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REGTIMESTAMP");

                    b.Property<DateTime>("DataRemessaArquivo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATREMARQ");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ENDEMAILCLI");

                    b.Property<int?>("EnderecoCobrancaCodigoEmpresa")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EnderecoCobrancaNumeroContrato")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int?>("EnderecoComercialCodigoEmpresa")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EnderecoComercialNumeroContrato")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int?>("EnderecoResidencialCodigoEmpresa")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EnderecoResidencialNumeroContrato")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("FiliacaoCliente")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FILIACAOCLI");

                    b.Property<string>("LocalTrabalho")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DCRLOCTRABCLI");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOMCLI");

                    b.Property<string>("NomeConjCliente")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOMCONJUCLI");

                    b.Property<string>("NomeContatoCliente")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOMCONTCLI");

                    b.Property<string>("NomeSocioCliente")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOMSOCCLI");

                    b.Property<string>("NumRgCliente")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NUMRGIDENTCLI");

                    b.Property<int>("RamalTelefoneComercial")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMRAMTELCOMCLI");

                    b.Property<string>("RegistroTransferido")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REGCKTRANSF");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("TIPSEXOCLI");

                    b.Property<long>("TelefoneCelular")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NUMTELCELCLI");

                    b.Property<long>("TelefoneCobranca")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NUMTELCOBRCLI");

                    b.Property<long>("TelefoneComercial")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NUMTELCOMCLI");

                    b.Property<long>("TelefoneContato")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NUMTELCONTCLI");

                    b.Property<long>("TelefoneFax")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NUMFAXCOMCLI");

                    b.Property<long>("TelefoneResidencial")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NUMTELRESCLI");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPPESSCLI");

                    b.Property<string>("TipoRegimeCasamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("TIPREGIMECASAMENTO");

                    b.HasKey("CodigoEmpresa", "NumeroContrato");

                    b.HasIndex("CpfCnpj");

                    b.HasIndex("EnderecoCobrancaCodigoEmpresa", "EnderecoCobrancaNumeroContrato");

                    b.HasIndex("EnderecoComercialCodigoEmpresa", "EnderecoComercialNumeroContrato");

                    b.HasIndex("EnderecoResidencialCodigoEmpresa", "EnderecoResidencialNumeroContrato");

                    b.HasIndex("CodigoEmpresa", "NumeroContrato", "CpfCnpj");

                    b.ToTable("CO001", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Debt", b =>
                {
                    b.Property<int>("CodigoEmpresa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODEMPRESA");

                    b.Property<string>("NumeroContrato")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("NUMCONTRDIV");

                    b.Property<string>("CodigoAgencia")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODAGENCIADIV");

                    b.Property<int?>("CodigoAreaCobranca")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODAREACOBRDIV");

                    b.Property<int>("CodigoCampanha")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODCAMPANHA");

                    b.Property<string>("CodigoCarteiraCobranca")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODCARTCOBR");

                    b.Property<string>("CodigoClassificacaoPdd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODCLASSPDDDIV");

                    b.Property<int?>("CodigoColigada")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODEMPRECOLG");

                    b.Property<long?>("CodigoDialing")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CODDIALING");

                    b.Property<int?>("CodigoEstrategia")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODESTRATEG");

                    b.Property<int?>("CodigoFaseCobranca")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODFASECOBRDIV");

                    b.Property<int>("CodigoFilial")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODFILIAL");

                    b.Property<int>("CodigoIndiceFinanceiro")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODINDFIN");

                    b.Property<long?>("CodigoInstrucaoCobranca")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CODINSTRCOBR");

                    b.Property<short?>("CodigoMotivoInadimplencia")
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("CODMOTIVINAD");

                    b.Property<string>("CodigoProduto")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODPRODCONTRDIV");

                    b.Property<int?>("CodigoScriptCobranca")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODSCRIPTCOB");

                    b.Property<string>("CodigoUsuario")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODUSERID");

                    b.Property<DateTime?>("DatContrDivida")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATCONTRDIV");

                    b.Property<DateTime?>("DataAgendamentoCobranca")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATAGENCOBR");

                    b.Property<DateTime?>("DataAtualizacaoRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATATUALREG");

                    b.Property<DateTime>("DataCadastroDivida")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATCADDIV");

                    b.Property<DateTime?>("DataDevolucaoDivida")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATDEVDIV");

                    b.Property<DateTime>("DataDirecionamentoContrato")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATCHEGBODERDIV");

                    b.Property<DateTime?>("DataEnquadramento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATENQRDIV");

                    b.Property<DateTime?>("DataHoraRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REGTIMESTAMP");

                    b.Property<DateTime?>("DataPerformance")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATPERFCOBRDIV");

                    b.Property<DateTime>("DataRemessa")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATREMARQ");

                    b.Property<DateTime?>("DataUltimaCobranca")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATULTCOBDIV");

                    b.Property<string>("DescricaoProduto")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DCRPRODCONTRDIV");

                    b.Property<string>("DescricaoSeguroProtecao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DCRSEGPROTDIV");

                    b.Property<string>("FaseDivida")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STAFASECOBRDIV");

                    b.Property<string>("InfComplDivida")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INFCOMPLDIV");

                    b.Property<string>("NomeConcAgenDiv")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOMCONCAGENDIV");

                    b.Property<int>("NumParcPlanoDivida")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMPARCPLANODIV");

                    b.Property<long>("NumeroCarteiraCobranca")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NUMCARTCOBDIV");

                    b.Property<long>("NumeroContratoCobranca")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NUMCONTRCOBDIV");

                    b.Property<string>("NumeroContratoVinculado")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NUMCONTRDIVVINC");

                    b.Property<int>("OrigemCobrancaDivida")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SITCOBDIV");

                    b.Property<short?>("QuantidadeContratoVinculado")
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("QTDVINCCONTRDIV");

                    b.Property<string>("RegistroTransferido")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REGCKTRANSF");

                    b.Property<int>("ReguaCobranca")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FASCOBRDIV");

                    b.Property<string>("ScoreContratante")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SCORECONTR");

                    b.Property<long?>("ScoreDivida")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SCOREDIVCOBR");

                    b.Property<string>("SitContratoDividaTerceiro")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SITCONTRDIVTERC");

                    b.Property<string>("SitInfoBaixaPastaBanco")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SITINFBXPASTABCO");

                    b.Property<string>("SitReferenciaContrato")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SITREFCONTRDIV");

                    b.Property<string>("SituacaoAcertoDivida")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SITACERTDIV");

                    b.Property<string>("SituacaoBloqueioAjuizamento")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SITBLOQAJUIZ");

                    b.Property<int>("SituacaoContratoAdversa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SITCONTRDIVADV");

                    b.Property<int>("SituacaoDividaCobranca")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SITDIVCOB");

                    b.Property<string>("SituacaoReclamacaoSac")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SITRECLSAC");

                    b.Property<string>("StatusTelefoneHigienizado")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATELHIGCONTRDIV");

                    b.Property<decimal>("TaxaFinanciamentoContrato")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TAXFINCONTRDIV");

                    b.Property<string>("TipoCobranca")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPCOBRDIV");

                    b.Property<string>("TipoContrato")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPCONTR");

                    b.Property<string>("TipoDivida")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("TIPODIVIDA");

                    b.Property<string>("TipoOperacaoCobranca")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPOPRCOBR");

                    b.Property<string>("TipoOperacaoContrato")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPOPRCONTRDIV");

                    b.Property<string>("TipoVinculoContrato")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPVINCCONTRDIV");

                    b.Property<decimal>("ValorDiaria")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VLRCPDIARIADIV");

                    b.Property<decimal?>("ValorPercentualPlanoPag")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VLRPERCPLPG");

                    b.Property<decimal?>("ValorRiscoContrato")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VLRRISCOCONTRDIV");

                    b.Property<decimal>("ValorSaldoDivida")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VLRSALDHISTPLDIV");

                    b.HasKey("CodigoEmpresa", "NumeroContrato");

                    b.HasIndex("NumeroCarteiraCobranca");

                    b.HasIndex("ScoreDivida");

                    b.HasIndex("SituacaoDividaCobranca", "CodigoEmpresa", "NumeroContrato");

                    b.ToTable("CO002", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Email", b =>
                {
                    b.Property<int>("CodigoEmpresa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODEMPRESA");

                    b.Property<string>("NumeroContrato")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("NUMCONTRDIV");

                    b.Property<string>("DescricaoEmail")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("DCREMAIL");

                    b.Property<string>("CodigoChaveBanco")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODCHAVEBANCO");

                    b.Property<string>("CodigoUsuarioAlteracao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODUSERIDALT");

                    b.Property<string>("CodigoUsuarioCadastro")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODUSERIDCAD");

                    b.Property<string>("CodigoUsuarioCancelar")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODUSERCANC");

                    b.Property<long>("CpfCnpj")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CODCPFCNPJ");

                    b.Property<DateTime>("DataCadastroEmail")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATCADEMAIL");

                    b.Property<DateTime?>("DataEmailAlterado")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATALTEMAIL");

                    b.Property<DateTime?>("DataEmailCancelado")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATCANCEMAIL");

                    b.Property<DateTime?>("DataHoraRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REGTIMESTAMP");

                    b.Property<DateTime>("DataRemessaArquivo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATREMARQ");

                    b.Property<string>("EmailPrincipal")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SITMAILPRINC");

                    b.Property<int?>("Higienizado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STAHIGEMAIL");

                    b.Property<string>("Observacao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OBSMAIL");

                    b.Property<int>("OrigemEmailCliente")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORGEMAILCLI");

                    b.Property<string>("RegistroTransferido")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REGCKTRANSF");

                    b.Property<string>("SitRobot")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SITROBOT");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STAEMAIL");

                    b.Property<int>("TipoEmail")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPOEMAIL");

                    b.HasKey("CodigoEmpresa", "NumeroContrato", "DescricaoEmail");

                    b.ToTable("CO125", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FilePattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("AllowedFileExtensions")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EXTARQUIVO");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("FileNamePattern")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INFORARQUIVO");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<int?>("ProcessingRoutineId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingRoutineId");

                    b.ToTable("FilePattern");
                });

            modelBuilder.Entity("Domain.Entities.Installment", b =>
                {
                    b.Property<int>("CodigoEmpresa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODEMPRESA");

                    b.Property<string>("NumeroContrato")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("NUMCONTRDIV");

                    b.Property<string>("CodigoFaseContratoParcela")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODFASCONTBPARC");

                    b.Property<int>("CodigoIndiceFinanceiro")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODINDFIN");

                    b.Property<long>("CodigoParcela")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CODPARC");

                    b.Property<DateTime>("DataAtualizacaoRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATATUALREG");

                    b.Property<DateTime?>("DataBaixa")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATBXPARC");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATCADPARC");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATDEVPARC");

                    b.Property<DateTime>("DataDirecionamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATCHEGBODERPARC");

                    b.Property<DateTime?>("DataEnquadramento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATVCTORGPARC");

                    b.Property<DateTime?>("DataHoraRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REGTIMESTAMP");

                    b.Property<DateTime?>("DataNotificacaoParcela")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATNOTIFPARC");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATPGTOPARC");

                    b.Property<DateTime>("DataRemessa")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATREMARQ");

                    b.Property<DateTime>("DataVencimentoParcela")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATVCTOPARC");

                    b.Property<long>("NumeroDocParcela")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NUMDOCPARC");

                    b.Property<long>("NumeroLoteParcela")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NUMLOTPARC");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMPARC");

                    b.Property<int?>("NumeroParcelaOriginal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMPARCORIGINAL");

                    b.Property<decimal>("PercentualVencimentoParcela")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("PERCVENCPARC");

                    b.Property<string>("RegistroTransferido")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REGCKTRANSF");

                    b.Property<int>("ReguaParcela")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FASCOBRDIV");

                    b.Property<decimal>("SaldoParcela")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("SLDPARC");

                    b.Property<long>("ScoreDivida")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SCOREDIVCOBR");

                    b.Property<int>("SituacaoBoletoParcela")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SITBOLPARC");

                    b.Property<int>("SituacaoCalculoVencimento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SITFORVCTOPARC");

                    b.Property<string>("SituacaoContratoAjuizado")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SITCONTRAJUIZ");

                    b.Property<int>("SituacaoParcela")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SITPARC");

                    b.Property<int>("SituacaoParcelaBloqueada")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SITBLOQPARC");

                    b.Property<string>("TipoAplicacaoParcela")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPAPPLPARC");

                    b.Property<int>("TipoBaixa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPBXPARC");

                    b.Property<int>("TipoCadastroParcela")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPCADPARC");

                    b.Property<string>("TipoMoeda")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPMOEDAPARC");

                    b.Property<int>("TipoParcela")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPPARC");

                    b.Property<decimal>("ValorCpParcela")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VLRCPPARC");

                    b.Property<decimal>("ValorDespesaParcela")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VLRDESPPARC");

                    b.Property<decimal>("ValorMoraParcela")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VLRMORAPARC");

                    b.Property<decimal>("ValorMultaParcela")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VLRMULTAPARC");

                    b.Property<decimal>("ValorPrincipalParcela")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VLRPRINCPARC");

                    b.HasKey("CodigoEmpresa", "NumeroContrato");

                    b.HasIndex("ScoreDivida");

                    b.HasIndex("SituacaoParcela");

                    b.HasIndex("DataDirecionamento", "CodigoEmpresa");

                    b.ToTable("CO003", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.InstitutionProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DefaultDirectory")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DCRDIR");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DCRPROC");

                    b.Property<int>("ProcessType")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPPROC");

                    b.HasKey("Id");

                    b.ToTable("InstitutionProfiles");
                });

            modelBuilder.Entity("Domain.Entities.Phone", b =>
                {
                    b.Property<int>("CodigoEmpresa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODEMPRESA");

                    b.Property<string>("NumeroContrato")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("NUMCONTRDIV");

                    b.Property<long>("Numero")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("BloqueioSms")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SITBLOQSMS");

                    b.Property<int>("Codigo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODTELCOBR");

                    b.Property<string>("CodigoArea")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODAREA");

                    b.Property<string>("CodigoChaveBanco")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODCHAVEBANCO");

                    b.Property<int?>("CodigoFornecedorPesq")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODEMPPESQ");

                    b.Property<long>("CpfCnpjCliente")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CODCPFCNPJCLI");

                    b.Property<DateTime?>("DataHoraCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATCADTELCOBR");

                    b.Property<DateTime?>("DataHoraCancelamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATCANCTELCOBR");

                    b.Property<DateTime?>("DataHoraRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REGTIMESTAMP");

                    b.Property<DateTime?>("DataRemessa")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATREMARQ");

                    b.Property<int>("Higienizado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STAHIGTELCOBR");

                    b.Property<string>("NumeroOriginal")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NUMTELORIGINAL");

                    b.Property<string>("Observacao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OBSTELCOBR");

                    b.Property<int>("Origem")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODORGTEL");

                    b.Property<short>("Prioridade")
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("SITPRIORTELCOBR");

                    b.Property<int?>("Score")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SCORETELCOBR");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATELCOBR");

                    b.Property<string>("UsuarioAlterou")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("USERALTERTELCOBR");

                    b.Property<string>("UsuarioCadastrou")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("USERCADTELCOBR");

                    b.Property<string>("UsuarioCancelou")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("USERCANCTELCOBR");

                    b.HasKey("CodigoEmpresa", "NumeroContrato", "Numero");

                    b.ToTable("CO090", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProcessingRoutine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("HasFooter")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("SITFOOTER");

                    b.Property<bool>("HasHeader")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("SITHEADER");

                    b.Property<int>("InstitutionProfileId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMPROC");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("STAPROC");

                    b.Property<bool>("IsPartitioned")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("SITSUPORTAPART");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ARQDESC");

                    b.Property<int?>("SchedulingId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("TotalParts")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QTDPARTES");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionProfileId");

                    b.HasIndex("SchedulingId");

                    b.ToTable("PR012", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Repetition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.PrimitiveCollection<string>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DIASSEMANA");

                    b.Property<TimeSpan?>("IntervalInSeconds")
                        .HasColumnType("INTERVAL DAY(8) TO SECOND(7)")
                        .HasColumnName("INTERVALO");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOMREPETICAO");

                    b.HasKey("Id");

                    b.ToTable("Repetition");
                });

            modelBuilder.Entity("Domain.Entities.Scheduling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("EndTime")
                        .HasColumnType("NVARCHAR2(48)")
                        .HasColumnName("HORAFIMAGENDA");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("STAAGENDA");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("LastVerificationDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATAULTVERIFICACAO");

                    b.Property<bool>("MustRepeat")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("REPETIRPROCESSO");

                    b.Property<int>("Priority")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRIORIDADE");

                    b.Property<int>("RepetitionId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODREPETICAO");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(48)")
                        .HasColumnName("HORAINIAGENDA");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("RepetitionId");

                    b.ToTable("PR018", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Client", b =>
                {
                    b.HasOne("Domain.Entities.Address", "EnderecoCobranca")
                        .WithMany()
                        .HasForeignKey("EnderecoCobrancaCodigoEmpresa", "EnderecoCobrancaNumeroContrato");

                    b.HasOne("Domain.Entities.Address", "EnderecoComercial")
                        .WithMany()
                        .HasForeignKey("EnderecoComercialCodigoEmpresa", "EnderecoComercialNumeroContrato");

                    b.HasOne("Domain.Entities.Address", "EnderecoResidencial")
                        .WithMany()
                        .HasForeignKey("EnderecoResidencialCodigoEmpresa", "EnderecoResidencialNumeroContrato");

                    b.Navigation("EnderecoCobranca");

                    b.Navigation("EnderecoComercial");

                    b.Navigation("EnderecoResidencial");
                });

            modelBuilder.Entity("Domain.Entities.FilePattern", b =>
                {
                    b.HasOne("Domain.Entities.ProcessingRoutine", null)
                        .WithMany("FilePatterns")
                        .HasForeignKey("ProcessingRoutineId");
                });

            modelBuilder.Entity("Domain.Entities.ProcessingRoutine", b =>
                {
                    b.HasOne("Domain.Entities.InstitutionProfile", "InstitutionProfile")
                        .WithMany("Routines")
                        .HasForeignKey("InstitutionProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Scheduling", null)
                        .WithMany("ProcessingRoutines")
                        .HasForeignKey("SchedulingId");

                    b.Navigation("InstitutionProfile");
                });

            modelBuilder.Entity("Domain.Entities.Scheduling", b =>
                {
                    b.HasOne("Domain.Entities.Repetition", "Repetition")
                        .WithMany()
                        .HasForeignKey("RepetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repetition");
                });

            modelBuilder.Entity("Domain.Entities.InstitutionProfile", b =>
                {
                    b.Navigation("Routines");
                });

            modelBuilder.Entity("Domain.Entities.ProcessingRoutine", b =>
                {
                    b.Navigation("FilePatterns");
                });

            modelBuilder.Entity("Domain.Entities.Scheduling", b =>
                {
                    b.Navigation("ProcessingRoutines");
                });
#pragma warning restore 612, 618
        }
    }
}
